use std::error::Error;

use super::super::validation::ValidatedOperations;
use super::write_generated;

pub(super) fn generate_api_key_client(
    operations: &ValidatedOperations,
) -> Result<(), Box<dyn Error>> {
    let operation = operations.operation("positron.v1.ApiKeyService/Manage")?;
    let path = operation.path();
    let request_limit = operation.request_limit();
    let response_limit = operation.response_limit();
    let source = format!(
        r#"// Generated by positron-api/build.rs from ApiKeyService/Manage in the canonical
// protobuf descriptor and HTTP mapping. Do not edit.
use std::io::Read;
use std::net::IpAddr;
use std::time::Duration;

pub struct ApiKeyServiceClient {{
    endpoint: String,
    client: reqwest::blocking::Client,
}}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ApiKeyServiceClientFailure {{
    InvalidRequest,
    AuthenticationRejected,
    StaleGeneration,
    IdempotencyConflict,
    KeyUnavailable,
    AdministrationUnavailable,
    Transport,
}}

impl std::fmt::Display for ApiKeyServiceClientFailure {{
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{
        formatter.write_str("API-key service request failed")
    }}
}}
impl std::error::Error for ApiKeyServiceClientFailure {{}}

impl ApiKeyServiceClient {{
    pub fn new(transport: super::ApiKeyTransport) -> Result<Self, ApiKeyServiceClientFailure> {{
        let (endpoint, builder) = match transport {{
            super::ApiKeyTransport::Tls {{ endpoint, server_name, trust_file }} => {{
                if server_name.is_empty() || server_name.len() > 253 || !server_name.bytes().all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'-' | b':')) {{
                    return Err(ApiKeyServiceClientFailure::Transport);
                }}
                let expected_identity = server_name.parse::<IpAddr>();
                if expected_identity.as_ref().is_ok_and(|identity| *identity != endpoint.ip()) {{
                    return Err(ApiKeyServiceClientFailure::Transport);
                }}
                let authority = match expected_identity {{
                    Ok(IpAddr::V6(_)) => format!("[{{server_name}}]"),
                    Ok(IpAddr::V4(_)) | Err(_) => server_name.clone(),
                }};
                let trust = crate::api_keys::read_bounded_trust_file(&trust_file)
                    .map_err(|_| ApiKeyServiceClientFailure::Transport)?;
                let certificate = reqwest::Certificate::from_pem(&trust)
                    .map_err(|_| ApiKeyServiceClientFailure::Transport)?;
                (format!("https://{{authority}}:{{}}", endpoint.port()), reqwest::blocking::Client::builder().add_root_certificate(certificate).resolve(&server_name, endpoint))
            }},
            super::ApiKeyTransport::PlaintextOptOut {{ endpoint }} => {{
                (format!("http://{{endpoint}}"), reqwest::blocking::Client::builder())
            }},
        }};
        let client = builder
            .connect_timeout(Duration::from_secs(5))
            .timeout(Duration::from_secs(5))
            .no_proxy()
            .build()
            .map_err(|_| ApiKeyServiceClientFailure::Transport)?;
        Ok(Self {{ endpoint, client }})
    }}

    pub fn manage(
        &self,
        bearer: &str,
        request: &super::ApiKeyRequest,
    ) -> Result<super::ApiKeyResponse, ApiKeyServiceClientFailure> {{
        let body = request.encode().map_err(|_| ApiKeyServiceClientFailure::Transport)?;
        if body.len() > {request_limit} {{
            return Err(ApiKeyServiceClientFailure::Transport);
        }}
        let url = format!("{{}}{{}}", self.endpoint, {path:?});
        let response = self.client.post(url)
            .bearer_auth(bearer)
            .header(reqwest::header::CONTENT_TYPE, "application/json")
            .body(body)
            .send()
            .map_err(|_| ApiKeyServiceClientFailure::Transport)?;
        let status = response.status().as_u16();
        let mut bytes = zeroize::Zeroizing::new(Vec::with_capacity({response_limit}));
        response.take(({response_limit} + 1) as u64)
            .read_to_end(&mut bytes)
            .map_err(|_| ApiKeyServiceClientFailure::Transport)?;
        if bytes.len() > {response_limit} {{
            return Err(ApiKeyServiceClientFailure::Transport);
        }}
        if !(200..300).contains(&status) {{
            let code = serde_json::from_slice::<serde_json::Value>(&bytes).ok()
                .and_then(|value| value.get("code")?.as_str().map(str::to_owned));
            return Err(match (status, code.as_deref()) {{
                (400, Some("invalid_request")) => ApiKeyServiceClientFailure::InvalidRequest,
                (401, Some("authentication_rejected")) => ApiKeyServiceClientFailure::AuthenticationRejected,
                (404, Some("key_unavailable")) => ApiKeyServiceClientFailure::KeyUnavailable,
                (409, Some("stale_generation")) => ApiKeyServiceClientFailure::StaleGeneration,
                (409, Some("idempotency_conflict")) => ApiKeyServiceClientFailure::IdempotencyConflict,
                (503, Some("administration_unavailable")) => ApiKeyServiceClientFailure::AdministrationUnavailable,
                _ => ApiKeyServiceClientFailure::Transport,
            }});
        }}
        super::ApiKeyResponse::decode(&bytes).map_err(|_| ApiKeyServiceClientFailure::Transport)
    }}
}}
"#
    );
    write_generated("api_key_service_client.rs", source)
}
