use std::error::Error;

use super::super::validation::ValidatedOperations;
use super::write_generated;

pub(super) fn generate_api_key_client(
    operations: &ValidatedOperations,
) -> Result<(), Box<dyn Error>> {
    let operation = operations.operation("positron.v1.ApiKeyService/Manage")?;
    let path = operation.path();
    let request_limit = operation.request_limit();
    let response_limit = operation.response_limit();
    let source = format!(
        r#"// Generated by positron-api/build.rs from ApiKeyService/Manage in the canonical
// protobuf descriptor and HTTP mapping. Do not edit.




pub struct ApiKeyServiceClient {{
    http: crate::http_client::HttpClient,
}}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ApiKeyServiceClientFailure {{
    InvalidRequest,
    AuthenticationRejected,
    StaleGeneration,
    IdempotencyConflict,
    KeyUnavailable,
    AdministrationUnavailable,
    Transport,
}}

impl std::fmt::Display for ApiKeyServiceClientFailure {{
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{
        formatter.write_str("API-key service request failed")
    }}
}}
impl std::error::Error for ApiKeyServiceClientFailure {{}}

impl ApiKeyServiceClient {{
    pub fn new(transport: super::ApiKeyTransport) -> Result<Self, ApiKeyServiceClientFailure> {{
        if let super::ApiKeyTransport::Tls {{ server_name, .. }} = &transport
            && !server_name.bytes().all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'-' | b':')) {{
            return Err(ApiKeyServiceClientFailure::Transport);
        }}
        let http = crate::http_client::HttpClient::new(transport).map_err(|_| ApiKeyServiceClientFailure::Transport)?;
        Ok(Self {{ http }})
    }}

    pub fn manage(
        &self,
        bearer: &str,
        request: &super::ApiKeyRequest,
    ) -> Result<super::ApiKeyResponse, ApiKeyServiceClientFailure> {{
        let body = request.encode().map_err(|_| ApiKeyServiceClientFailure::Transport)?;
        if body.len() > {request_limit} {{
            return Err(ApiKeyServiceClientFailure::Transport);
        }}
        let (status, bytes) = self.http.post(bearer, {path:?}, body, {response_limit}).map_err(|_| ApiKeyServiceClientFailure::Transport)?;
        if !(200..300).contains(&status) {{
            let code = serde_json::from_slice::<serde_json::Value>(&bytes).ok()
                .and_then(|value| value.get("code")?.as_str().map(str::to_owned));
            return Err(match (status, code.as_deref()) {{
                (400, Some("invalid_request")) => ApiKeyServiceClientFailure::InvalidRequest,
                (401, Some("authentication_rejected")) => ApiKeyServiceClientFailure::AuthenticationRejected,
                (404, Some("key_unavailable")) => ApiKeyServiceClientFailure::KeyUnavailable,
                (409, Some("stale_generation")) => ApiKeyServiceClientFailure::StaleGeneration,
                (409, Some("idempotency_conflict")) => ApiKeyServiceClientFailure::IdempotencyConflict,
                (503, Some("administration_unavailable")) => ApiKeyServiceClientFailure::AdministrationUnavailable,
                _ => ApiKeyServiceClientFailure::Transport,
            }});
        }}
        super::ApiKeyResponse::decode(&bytes).map_err(|_| ApiKeyServiceClientFailure::Transport)
    }}
}}
"#
    );
    write_generated("api_key_service_client.rs", source)
}
