use std::error::Error;

use super::super::validation::ValidatedOperations;
use super::write_generated;

pub(super) fn generate_maintenance_client(
    operations: &ValidatedOperations,
) -> Result<(), Box<dyn Error>> {
    let operation = operations.operation("positron.v1.MaintenanceService/Status")?;
    let path = operation.path();
    let request_limit = operation.request_limit();
    let response_limit = operation.response_limit();
    let explain = operations.operation("positron.v1.MaintenanceService/Explain")?;
    let explain_path = explain.path();
    let explain_request_limit = explain.request_limit();
    let explain_response_limit = explain.response_limit();
    let run = operations.operation("positron.v1.MaintenanceService/Run")?;
    let run_path = run.path();
    let run_request_limit = run.request_limit();
    let run_response_limit = run.response_limit();
    let pause = operations.operation("positron.v1.MaintenanceService/Pause")?;
    let pause_path = pause.path();
    let pause_request_limit = pause.request_limit();
    let pause_response_limit = pause.response_limit();
    let resume = operations.operation("positron.v1.MaintenanceService/Resume")?;
    let resume_path = resume.path();
    let resume_request_limit = resume.request_limit();
    let resume_response_limit = resume.response_limit();
    let window = operations.operation("positron.v1.MaintenanceService/Window")?;
    let window_path = window.path();
    let window_request_limit = window.request_limit();
    let window_response_limit = window.response_limit();
    let verify = operations.operation("positron.v1.MaintenanceService/Verify")?;
    let verify_path = verify.path();
    let verify_request_limit = verify.request_limit();
    let verify_response_limit = verify.response_limit();
    let source = format!(
        r#"// Generated by positron-api/build.rs from MaintenanceService in the canonical protobuf descriptor and HTTP mapping. Do not edit.
use std::io::Read;
use std::time::Duration;
#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub enum MaintenanceServiceClientFailure {{ InvalidRequest, AuthenticationRejected, SourceUnavailable, TaskUnavailable, PreconditionFailed, IdempotencyConflict, AdministrationUnavailable, Transport }}
impl std::fmt::Display for MaintenanceServiceClientFailure {{ fn fmt(&self, f:&mut std::fmt::Formatter<'_>)->std::fmt::Result {{ f.write_str("maintenance service request failed") }} }}
impl std::error::Error for MaintenanceServiceClientFailure {{}}
pub struct MaintenanceServiceClient {{ endpoint:String, client:reqwest::blocking::Client }}
impl MaintenanceServiceClient {{
pub fn new(transport:super::MaintenanceTransport)->Result<Self,MaintenanceServiceClientFailure>{{let(endpoint,builder)=match transport{{super::MaintenanceTransport::PlaintextOptOut{{endpoint}}=>(format!("http://{{endpoint}}"),reqwest::blocking::Client::builder()),super::MaintenanceTransport::Tls{{endpoint,server_name,trust_file}}=>{{let ip=server_name.parse::<std::net::IpAddr>();if server_name.is_empty()||server_name.len()>253||ip.as_ref().is_ok_and(|ip|*ip!=endpoint.ip()){{return Err(MaintenanceServiceClientFailure::Transport)}}let trust=std::fs::read(trust_file).map_err(|_|MaintenanceServiceClientFailure::Transport)?;let certificate=reqwest::Certificate::from_pem(&trust).map_err(|_|MaintenanceServiceClientFailure::Transport)?;let authority=match ip{{Ok(std::net::IpAddr::V6(_))=>format!("[{{server_name}}]"),_=>server_name.clone()}};(format!("https://{{authority}}:{{}}",endpoint.port()),reqwest::blocking::Client::builder().add_root_certificate(certificate).resolve(&server_name,endpoint))}}}};Ok(Self{{endpoint,client:builder.connect_timeout(Duration::from_secs(5)).timeout(Duration::from_secs(5)).no_proxy().build().map_err(|_|MaintenanceServiceClientFailure::Transport)?}})}}
pub fn status(&self,bearer:&str,request:&super::MaintenanceStatusRequest)->Result<super::MaintenanceStatusResponse,MaintenanceServiceClientFailure>{{let body=serde_json::to_vec(request).map_err(|_|MaintenanceServiceClientFailure::InvalidRequest)?;if body.len()>{request_limit}{{return Err(MaintenanceServiceClientFailure::InvalidRequest)}}let response=self.client.post(format!("{{}}{{}}",self.endpoint,{path:?})).bearer_auth(bearer).header(reqwest::header::CONTENT_TYPE,"application/json").body(body).send().map_err(|_|MaintenanceServiceClientFailure::Transport)?;let status=response.status().as_u16();let mut bytes=Vec::with_capacity({response_limit});response.take(({response_limit}+1)as u64).read_to_end(&mut bytes).map_err(|_|MaintenanceServiceClientFailure::Transport)?;if bytes.len()>{response_limit}{{return Err(MaintenanceServiceClientFailure::Transport)}}
if !(200..300).contains(&status){{let code=serde_json::from_slice::<serde_json::Value>(&bytes).ok().and_then(|value|value.get("code")?.as_str().map(str::to_owned));return Err(match(status,code.as_deref()){{(400,Some("invalid_request"))=>MaintenanceServiceClientFailure::InvalidRequest,(401,Some("authentication_rejected"))=>MaintenanceServiceClientFailure::AuthenticationRejected,(503,Some("administration_unavailable"))=>MaintenanceServiceClientFailure::AdministrationUnavailable,_=>MaintenanceServiceClientFailure::Transport}})}}super::MaintenanceStatusResponse::decode(&bytes).map_err(|_|MaintenanceServiceClientFailure::Transport)}}
pub fn explain(&self,bearer:&str,request:&super::MaintenanceExplainRequest)->Result<super::MaintenanceExplainResponse,MaintenanceServiceClientFailure>{{let body=serde_json::to_vec(request).map_err(|_|MaintenanceServiceClientFailure::InvalidRequest)?;if body.len()>{explain_request_limit}{{return Err(MaintenanceServiceClientFailure::InvalidRequest)}}let response=self.client.post(format!("{{}}{{}}",self.endpoint,{explain_path:?})).bearer_auth(bearer).header(reqwest::header::CONTENT_TYPE,"application/json").body(body).send().map_err(|_|MaintenanceServiceClientFailure::Transport)?;let status=response.status().as_u16();let mut bytes=Vec::with_capacity({explain_response_limit});response.take(({explain_response_limit}+1)as u64).read_to_end(&mut bytes).map_err(|_|MaintenanceServiceClientFailure::Transport)?;if bytes.len()>{explain_response_limit}{{return Err(MaintenanceServiceClientFailure::Transport)}}
if !(200..300).contains(&status){{let code=serde_json::from_slice::<serde_json::Value>(&bytes).ok().and_then(|value|value.get("code")?.as_str().map(str::to_owned));return Err(match(status,code.as_deref()){{(400,Some("invalid_request"))=>MaintenanceServiceClientFailure::InvalidRequest,(401,Some("authentication_rejected"))=>MaintenanceServiceClientFailure::AuthenticationRejected,(404,Some("task_unavailable"))=>MaintenanceServiceClientFailure::TaskUnavailable,(503,Some("administration_unavailable"))=>MaintenanceServiceClientFailure::AdministrationUnavailable,_=>MaintenanceServiceClientFailure::Transport}})}}super::MaintenanceExplainResponse::decode(&bytes).map_err(|_|MaintenanceServiceClientFailure::Transport)}}
pub fn run(&self,bearer:&str,request:&super::MaintenanceRunRequest)->Result<super::MaintenanceRunResponse,MaintenanceServiceClientFailure>{{let body=request.encode().map_err(|_|MaintenanceServiceClientFailure::InvalidRequest)?;if body.len()>{run_request_limit}{{return Err(MaintenanceServiceClientFailure::InvalidRequest)}}let response=self.client.post(format!("{{}}{{}}",self.endpoint,{run_path:?})).bearer_auth(bearer).header(reqwest::header::CONTENT_TYPE,"application/json").body(body).send().map_err(|_|MaintenanceServiceClientFailure::Transport)?;let status=response.status().as_u16();let mut bytes=Vec::with_capacity({run_response_limit});response.take(({run_response_limit}+1)as u64).read_to_end(&mut bytes).map_err(|_|MaintenanceServiceClientFailure::Transport)?;if bytes.len()>{run_response_limit}{{return Err(MaintenanceServiceClientFailure::Transport)}}
if !(200..300).contains(&status){{let code=serde_json::from_slice::<serde_json::Value>(&bytes).ok().and_then(|value|value.get("code")?.as_str().map(str::to_owned));return Err(match(status,code.as_deref()){{(400,Some("invalid_request"))=>MaintenanceServiceClientFailure::InvalidRequest,(401,Some("authentication_rejected"))=>MaintenanceServiceClientFailure::AuthenticationRejected,(404,Some("source_unavailable"))=>MaintenanceServiceClientFailure::SourceUnavailable,(409,Some("idempotency_conflict"))=>MaintenanceServiceClientFailure::IdempotencyConflict,(503,Some("administration_unavailable"))=>MaintenanceServiceClientFailure::AdministrationUnavailable,_=>MaintenanceServiceClientFailure::Transport}})}}super::MaintenanceRunResponse::decode(&bytes).map_err(|_|MaintenanceServiceClientFailure::Transport)}}
pub fn pause(&self,bearer:&str,request:&super::MaintenancePauseRequest)->Result<super::MaintenanceControlResponse,MaintenanceServiceClientFailure>{{let body=request.encode().map_err(|_|MaintenanceServiceClientFailure::InvalidRequest)?;if body.len()>{pause_request_limit}{{return Err(MaintenanceServiceClientFailure::InvalidRequest)}}let response=self.client.post(format!("{{}}{{}}",self.endpoint,{pause_path:?})).bearer_auth(bearer).header(reqwest::header::CONTENT_TYPE,"application/json").body(body).send().map_err(|_|MaintenanceServiceClientFailure::Transport)?;let status=response.status().as_u16();let mut bytes=Vec::with_capacity({pause_response_limit});response.take(({pause_response_limit}+1)as u64).read_to_end(&mut bytes).map_err(|_|MaintenanceServiceClientFailure::Transport)?;if bytes.len()>{pause_response_limit}{{return Err(MaintenanceServiceClientFailure::Transport)}}
if !(200..300).contains(&status){{let code=serde_json::from_slice::<serde_json::Value>(&bytes).ok().and_then(|value|value.get("code")?.as_str().map(str::to_owned));return Err(match(status,code.as_deref()){{(400,Some("invalid_request"))=>MaintenanceServiceClientFailure::InvalidRequest,(401,Some("authentication_rejected"))=>MaintenanceServiceClientFailure::AuthenticationRejected,(404,Some("task_unavailable"))=>MaintenanceServiceClientFailure::TaskUnavailable,(409,Some("precondition_failed"))=>MaintenanceServiceClientFailure::PreconditionFailed,(409,Some("idempotency_conflict"))=>MaintenanceServiceClientFailure::IdempotencyConflict,(503,Some("administration_unavailable"))=>MaintenanceServiceClientFailure::AdministrationUnavailable,_=>MaintenanceServiceClientFailure::Transport}})}}super::MaintenanceControlResponse::decode(&bytes).map_err(|_|MaintenanceServiceClientFailure::Transport)}}
pub fn resume(&self,bearer:&str,request:&super::MaintenanceResumeRequest)->Result<super::MaintenanceControlResponse,MaintenanceServiceClientFailure>{{let body=request.encode().map_err(|_|MaintenanceServiceClientFailure::InvalidRequest)?;if body.len()>{resume_request_limit}{{return Err(MaintenanceServiceClientFailure::InvalidRequest)}}let response=self.client.post(format!("{{}}{{}}",self.endpoint,{resume_path:?})).bearer_auth(bearer).header(reqwest::header::CONTENT_TYPE,"application/json").body(body).send().map_err(|_|MaintenanceServiceClientFailure::Transport)?;let status=response.status().as_u16();let mut bytes=Vec::with_capacity({resume_response_limit});response.take(({resume_response_limit}+1)as u64).read_to_end(&mut bytes).map_err(|_|MaintenanceServiceClientFailure::Transport)?;if bytes.len()>{resume_response_limit}{{return Err(MaintenanceServiceClientFailure::Transport)}}
if !(200..300).contains(&status){{let code=serde_json::from_slice::<serde_json::Value>(&bytes).ok().and_then(|value|value.get("code")?.as_str().map(str::to_owned));return Err(match(status,code.as_deref()){{(400,Some("invalid_request"))=>MaintenanceServiceClientFailure::InvalidRequest,(401,Some("authentication_rejected"))=>MaintenanceServiceClientFailure::AuthenticationRejected,(404,Some("task_unavailable"))=>MaintenanceServiceClientFailure::TaskUnavailable,(409,Some("precondition_failed"))=>MaintenanceServiceClientFailure::PreconditionFailed,(409,Some("idempotency_conflict"))=>MaintenanceServiceClientFailure::IdempotencyConflict,(503,Some("administration_unavailable"))=>MaintenanceServiceClientFailure::AdministrationUnavailable,_=>MaintenanceServiceClientFailure::Transport}})}}super::MaintenanceControlResponse::decode(&bytes).map_err(|_|MaintenanceServiceClientFailure::Transport)}}
pub fn window(&self,bearer:&str,request:&super::MaintenanceWindowRequest)->Result<super::MaintenanceWindowResponse,MaintenanceServiceClientFailure>{{let body=request.encode().map_err(|_|MaintenanceServiceClientFailure::InvalidRequest)?;if body.len()>{window_request_limit}{{return Err(MaintenanceServiceClientFailure::InvalidRequest)}}let response=self.client.post(format!("{{}}{{}}",self.endpoint,{window_path:?})).bearer_auth(bearer).header(reqwest::header::CONTENT_TYPE,"application/json").body(body).send().map_err(|_|MaintenanceServiceClientFailure::Transport)?;let status=response.status().as_u16();let mut bytes=Vec::with_capacity({window_response_limit});response.take(({window_response_limit}+1)as u64).read_to_end(&mut bytes).map_err(|_|MaintenanceServiceClientFailure::Transport)?;if bytes.len()>{window_response_limit}{{return Err(MaintenanceServiceClientFailure::Transport)}}
if !(200..300).contains(&status){{let code=serde_json::from_slice::<serde_json::Value>(&bytes).ok().and_then(|value|value.get("code")?.as_str().map(str::to_owned));return Err(match(status,code.as_deref()){{(400,Some("invalid_request"))=>MaintenanceServiceClientFailure::InvalidRequest,(401,Some("authentication_rejected"))=>MaintenanceServiceClientFailure::AuthenticationRejected,(409,Some("precondition_failed"))=>MaintenanceServiceClientFailure::PreconditionFailed,(409,Some("idempotency_conflict"))=>MaintenanceServiceClientFailure::IdempotencyConflict,(503,Some("administration_unavailable"))=>MaintenanceServiceClientFailure::AdministrationUnavailable,_=>MaintenanceServiceClientFailure::Transport}})}}super::MaintenanceWindowResponse::decode(&bytes).map_err(|_|MaintenanceServiceClientFailure::Transport)}}
pub fn verify(&self,bearer:&str,request:&super::OnlineVerificationRequest)->Result<super::OnlineVerificationReport,MaintenanceServiceClientFailure>{{let body=request.encode().map_err(|_|MaintenanceServiceClientFailure::InvalidRequest)?;if body.len()>{verify_request_limit}{{return Err(MaintenanceServiceClientFailure::InvalidRequest)}}let response=self.client.post(format!("{{}}{{}}",self.endpoint,{verify_path:?})).bearer_auth(bearer).header(reqwest::header::CONTENT_TYPE,"application/json").body(body).send().map_err(|_|MaintenanceServiceClientFailure::Transport)?;let status=response.status().as_u16();let mut bytes=Vec::with_capacity({verify_response_limit});response.take(({verify_response_limit}+1)as u64).read_to_end(&mut bytes).map_err(|_|MaintenanceServiceClientFailure::Transport)?;if bytes.len()>{verify_response_limit}{{return Err(MaintenanceServiceClientFailure::Transport)}}
if !(200..300).contains(&status){{let code=serde_json::from_slice::<serde_json::Value>(&bytes).ok().and_then(|value|value.get("code")?.as_str().map(str::to_owned));return Err(match(status,code.as_deref()){{(400,Some("invalid_request"))=>MaintenanceServiceClientFailure::InvalidRequest,(401,Some("authentication_rejected"))=>MaintenanceServiceClientFailure::AuthenticationRejected,(404,Some("source_unavailable"))=>MaintenanceServiceClientFailure::SourceUnavailable,(503,Some("administration_unavailable"))=>MaintenanceServiceClientFailure::AdministrationUnavailable,_=>MaintenanceServiceClientFailure::Transport}})}}super::OnlineVerificationReport::decode(&bytes).map_err(|_|MaintenanceServiceClientFailure::Transport)}}
}}
"#,
        verify_path = verify_path,
        verify_request_limit = verify_request_limit,
        verify_response_limit = verify_response_limit,
        pause_path = pause_path,
        pause_request_limit = pause_request_limit,
        pause_response_limit = pause_response_limit,
        resume_path = resume_path,
        resume_request_limit = resume_request_limit,
        resume_response_limit = resume_response_limit,
        window_path = window_path,
        window_request_limit = window_request_limit,
        window_response_limit = window_response_limit,
        explain_path = explain_path,
        explain_request_limit = explain_request_limit,
        explain_response_limit = explain_response_limit,
        run_path = run_path,
        run_request_limit = run_request_limit,
        run_response_limit = run_response_limit
    );
    write_generated("maintenance_service_client.rs", source)
}
