use std::error::Error;

use super::super::validation::ValidatedOperations;
use super::write_generated;

pub(super) fn generate_policy_activate_client(
    operations: &ValidatedOperations,
) -> Result<(), Box<dyn Error>> {
    let operation = operations.operation("positron.v1.PolicyService/Activate")?;
    let path = operation.path();
    let request_limit = operation.request_limit();
    let response_limit = operation.response_limit();
    let source = format!(
        r#"// Generated by positron-api/build.rs from PolicyService/Activate in the canonical
// protobuf descriptor and HTTP mapping. Do not edit.


pub const MAX_ACTIVATE_REQUEST_BYTES: usize = {request_limit};
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum PolicyActivateServiceClientFailure {{
    InvalidRequest,
    AuthenticationRejected,
    StaleGeneration {{ resource_generation: u64, semantic_diff: String }},
    IdempotencyConflict,
    AdministrationUnavailable,
    Transport,
}}
impl std::fmt::Display for PolicyActivateServiceClientFailure {{
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{ formatter.write_str("policy activate service request failed") }}
}}
impl std::error::Error for PolicyActivateServiceClientFailure {{}}
pub struct PolicyActivateServiceClient {{ http: crate::http_client::HttpClient,}}
impl PolicyActivateServiceClient {{
    pub fn new(transport: super::PolicyPreviewTransport) -> Result<Self, PolicyActivateServiceClientFailure> {{
        let http = crate::http_client::HttpClient::new(transport).map_err(|_| PolicyActivateServiceClientFailure::Transport)?;
        Ok(Self {{ http }})
    }}
    pub fn activate(&self, bearer: &str, request: &super::PolicyActivateRequest) -> Result<super::PolicyActivateResponse, PolicyActivateServiceClientFailure> {{
        let body = request.encode()?;
        if body.len() > MAX_ACTIVATE_REQUEST_BYTES {{ return Err(PolicyActivateServiceClientFailure::InvalidRequest); }}
        let (status, bytes) = self.http.post(bearer, {path:?}, body, {response_limit}).map_err(|_| PolicyActivateServiceClientFailure::Transport)?;
        if !(200..300).contains(&status) {{
            let value = serde_json::from_slice::<serde_json::Value>(&bytes).ok();
            let code = value.as_ref().and_then(|value| value.get("code")?.as_str());
            return Err(match (status, code) {{
                (400, Some("invalid_request")) => PolicyActivateServiceClientFailure::InvalidRequest,
                (401, Some("authentication_rejected")) => PolicyActivateServiceClientFailure::AuthenticationRejected,
                (409, Some("stale_generation")) => {{
                    let generation = value.as_ref().and_then(|value| value.get("resource_generation")?.as_u64());
                    let semantic_diff = value.as_ref().and_then(|value| value.get("semantic_diff")?.as_str()).filter(|value| !value.is_empty() && value.len() <= 1024);
                    match (generation, semantic_diff) {{
                        (Some(resource_generation), Some(semantic_diff)) if resource_generation != 0 => PolicyActivateServiceClientFailure::StaleGeneration {{ resource_generation, semantic_diff: semantic_diff.to_owned() }},
                        _ => PolicyActivateServiceClientFailure::Transport,
                    }}
                }},
                (409, Some("idempotency_conflict")) => PolicyActivateServiceClientFailure::IdempotencyConflict,
                (503, Some("administration_unavailable")) => PolicyActivateServiceClientFailure::AdministrationUnavailable,
                _ => PolicyActivateServiceClientFailure::Transport,
            }});
        }}
        super::PolicyActivateResponse::decode(&bytes)
    }}
}}
"#,
        path = path,
        request_limit = request_limit,
        response_limit = response_limit,
    );
    write_generated("policy_activate_service_client.rs", source)
}
