use std::error::Error;

use super::super::validation::ValidatedOperations;
use super::write_generated;

pub(super) fn generate_policy_diff_client(
    operations: &ValidatedOperations,
) -> Result<(), Box<dyn Error>> {
    let operation = operations.operation("positron.v1.PolicyService/Diff")?;
    let path = operation.path();
    let request_limit = operation.request_limit();
    let response_limit = operation.response_limit();
    let source = format!(
        r#"// Generated by positron-api/build.rs from PolicyService/Diff in the canonical
// protobuf descriptor and HTTP mapping. Do not edit.
use std::io::Read;
use std::time::Duration;
pub const MAX_DIFF_REQUEST_BYTES: usize = {request_limit};
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PolicyDiffServiceClientFailure {{
    InvalidRequest,
    AuthenticationRejected,
    AdministrationUnavailable,
    Transport,
}}
impl std::fmt::Display for PolicyDiffServiceClientFailure {{
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{ formatter.write_str("policy diff service request failed") }}
}}
impl std::error::Error for PolicyDiffServiceClientFailure {{}}
pub struct PolicyDiffServiceClient {{ endpoint: String, client: reqwest::blocking::Client }}
impl PolicyDiffServiceClient {{
    pub fn new(transport: super::PolicyPreviewTransport) -> Result<Self, PolicyDiffServiceClientFailure> {{
        let (endpoint, builder) = match transport {{
            super::PolicyPreviewTransport::PlaintextOptOut {{ endpoint }} => (format!("http://{{endpoint}}"), reqwest::blocking::Client::builder()),
            super::PolicyPreviewTransport::Tls {{ endpoint, server_name, trust_file }} => {{
                let identity = server_name.parse::<std::net::IpAddr>();
                if server_name.is_empty() || server_name.len() > 253 || identity.as_ref().is_ok_and(|ip| *ip != endpoint.ip()) {{ return Err(PolicyDiffServiceClientFailure::Transport); }}
                let authority = match identity {{ Ok(std::net::IpAddr::V6(_)) => format!("[{{server_name}}]"), _ => server_name.clone() }};
                let trust = crate::api_keys::read_bounded_trust_file(&trust_file).map_err(|_| PolicyDiffServiceClientFailure::Transport)?;
                let certificate = reqwest::Certificate::from_pem(&trust).map_err(|_| PolicyDiffServiceClientFailure::Transport)?;
                (format!("https://{{authority}}:{{}}", endpoint.port()), reqwest::blocking::Client::builder().add_root_certificate(certificate).resolve(&server_name, endpoint))
            }},
        }};
        Ok(Self {{ endpoint, client: builder.connect_timeout(Duration::from_secs(5)).timeout(Duration::from_secs(5)).no_proxy().build().map_err(|_| PolicyDiffServiceClientFailure::Transport)? }})
    }}
    pub fn diff(&self, bearer: &str, request: &super::PolicyDiffRequest) -> Result<super::PolicyDiffResponse, PolicyDiffServiceClientFailure> {{
        let body = request.encode()?;
        if body.len() > MAX_DIFF_REQUEST_BYTES {{ return Err(PolicyDiffServiceClientFailure::InvalidRequest); }}
        let response = self.client.post(format!("{{}}{path}", self.endpoint)).bearer_auth(bearer).header(reqwest::header::CONTENT_TYPE, "application/json").body(body).send().map_err(|_| PolicyDiffServiceClientFailure::Transport)?;
        let status = response.status().as_u16();
        let mut bytes = Vec::with_capacity({response_limit});
        response.take(({response_limit} + 1) as u64).read_to_end(&mut bytes).map_err(|_| PolicyDiffServiceClientFailure::Transport)?;
        if bytes.len() > {response_limit} {{ return Err(PolicyDiffServiceClientFailure::Transport); }}
        if !(200..300).contains(&status) {{
            let code = serde_json::from_slice::<serde_json::Value>(&bytes).ok().and_then(|value| value.get("code")?.as_str().map(str::to_owned));
            return Err(match (status, code.as_deref()) {{
                (400, Some("invalid_request")) => PolicyDiffServiceClientFailure::InvalidRequest,
                (401, Some("authentication_rejected")) => PolicyDiffServiceClientFailure::AuthenticationRejected,
                (503, Some("administration_unavailable")) => PolicyDiffServiceClientFailure::AdministrationUnavailable,
                _ => PolicyDiffServiceClientFailure::Transport,
            }});
        }}
        super::PolicyDiffResponse::decode(&bytes)
    }}
}}
"#,
        path = path,
        request_limit = request_limit,
        response_limit = response_limit,
    );
    write_generated("policy_diff_service_client.rs", source)
}
