use std::error::Error;

use super::super::validation::ValidatedOperations;
use super::write_generated;

pub(super) fn generate_policy_explain_client(
    operations: &ValidatedOperations,
) -> Result<(), Box<dyn Error>> {
    let operation = operations.operation("positron.v1.PolicyService/Explain")?;
    let path = operation.path();
    let request_limit = operation.request_limit();
    let response_limit = operation.response_limit();
    let source = format!(
        r#"// Generated by positron-api/build.rs from PolicyService/Explain in the canonical
// protobuf descriptor and HTTP mapping. Do not edit.


pub const MAX_EXPLAIN_REQUEST_BYTES: usize = {request_limit};
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PolicyExplainServiceClientFailure {{
    InvalidRequest,
    AuthenticationRejected,
    AdministrationUnavailable,
    Transport,
}}
impl std::fmt::Display for PolicyExplainServiceClientFailure {{
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{ formatter.write_str("policy explain service request failed") }}
}}
impl std::error::Error for PolicyExplainServiceClientFailure {{}}
pub struct PolicyExplainServiceClient {{ http: crate::http_client::HttpClient,}}
impl PolicyExplainServiceClient {{
    pub fn new(transport: super::PolicyPreviewTransport) -> Result<Self, PolicyExplainServiceClientFailure> {{
        let http = crate::http_client::HttpClient::new(transport).map_err(|_| PolicyExplainServiceClientFailure::Transport)?;
        Ok(Self {{ http }})
    }}
    pub fn explain(&self, bearer: &str, request: &super::PolicyExplainRequest) -> Result<super::PolicyExplainResponse, PolicyExplainServiceClientFailure> {{
        let body = request.encode().map_err(|_| PolicyExplainServiceClientFailure::InvalidRequest)?;
        if body.len() > MAX_EXPLAIN_REQUEST_BYTES {{ return Err(PolicyExplainServiceClientFailure::InvalidRequest); }}
        let (status, bytes) = self.http.post(bearer, {path:?}, body, {response_limit}).map_err(|_| PolicyExplainServiceClientFailure::Transport)?;
        if !(200..300).contains(&status) {{
            let code = serde_json::from_slice::<serde_json::Value>(&bytes).ok().and_then(|value| value.get("code")?.as_str().map(str::to_owned));
            return Err(match (status, code.as_deref()) {{
                (400, Some("invalid_request")) => PolicyExplainServiceClientFailure::InvalidRequest,
                (401, Some("authentication_rejected")) => PolicyExplainServiceClientFailure::AuthenticationRejected,
                (503, Some("administration_unavailable")) => PolicyExplainServiceClientFailure::AdministrationUnavailable,
                _ => PolicyExplainServiceClientFailure::Transport,
            }});
        }}
        super::PolicyExplainResponse::decode(&bytes).map_err(|_| PolicyExplainServiceClientFailure::Transport)
    }}
}}
"#,
        path = path,
        request_limit = request_limit,
        response_limit = response_limit,
    );
    write_generated("policy_explain_service_client.rs", source)
}
