use std::error::Error;

use super::super::validation::ValidatedOperations;
use super::write_generated;

pub(super) fn generate_policy_test_client(
    operations: &ValidatedOperations,
) -> Result<(), Box<dyn Error>> {
    let operation = operations.operation("positron.v1.PolicyService/Test")?;
    let path = operation.path();
    let request_limit = operation.request_limit();
    let response_limit = operation.response_limit();
    let source = format!(
        r#"// Generated by positron-api/build.rs from PolicyService/Test in the canonical
// protobuf descriptor and HTTP mapping. Do not edit.


pub const MAX_TEST_REQUEST_BYTES: usize = {request_limit};
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PolicyTestServiceClientFailure {{
    InvalidRequest,
    AuthenticationRejected,
    AdministrationUnavailable,
    Transport,
}}
impl std::fmt::Display for PolicyTestServiceClientFailure {{
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{
        formatter.write_str("policy test service request failed")
    }}
}}
impl std::error::Error for PolicyTestServiceClientFailure {{}}

pub struct PolicyTestServiceClient {{
    http: crate::http_client::HttpClient,
}}
impl PolicyTestServiceClient {{
    pub fn new(transport: super::PolicyPreviewTransport) -> Result<Self, PolicyTestServiceClientFailure> {{
        let http = crate::http_client::HttpClient::new(transport).map_err(|_| PolicyTestServiceClientFailure::Transport)?;
        Ok(Self {{ http }})
    }}
    pub fn test(&self, bearer: &str, request: &super::PolicyTestRequest) -> Result<super::PolicyTestResponse, PolicyTestServiceClientFailure> {{
        let body = request.encode()?;
        if body.len() > MAX_TEST_REQUEST_BYTES {{
            return Err(PolicyTestServiceClientFailure::InvalidRequest);
        }}
        let (status, bytes) = self.http.post(bearer, {path:?}, body, {response_limit}).map_err(|_| PolicyTestServiceClientFailure::Transport)?;
        if !(200..300).contains(&status) {{
            let code = serde_json::from_slice::<serde_json::Value>(&bytes).ok().and_then(|value| value.get("code")?.as_str().map(str::to_owned));
            return Err(match (status, code.as_deref()) {{
                (400, Some("invalid_request")) => PolicyTestServiceClientFailure::InvalidRequest,
                (401, Some("authentication_rejected")) => PolicyTestServiceClientFailure::AuthenticationRejected,
                (503, Some("administration_unavailable")) => PolicyTestServiceClientFailure::AdministrationUnavailable,
                _ => PolicyTestServiceClientFailure::Transport,
            }});
        }}
        super::PolicyTestResponse::decode(&bytes)
    }}
}}
"#,
        path = path,
        request_limit = request_limit,
        response_limit = response_limit,
    );
    write_generated("policy_test_service_client.rs", source)
}
