use std::error::Error;

use super::super::validation::ValidatedOperations;
use super::write_generated;

pub(super) fn generate_policy_diff_client(
    operations: &ValidatedOperations,
) -> Result<(), Box<dyn Error>> {
    let operation = operations.operation("positron.v1.PolicyService/Diff")?;
    let path = operation.path();
    let request_limit = operation.request_limit();
    let response_limit = operation.response_limit();
    let source = format!(
        r#"// Generated by positron-api/build.rs from PolicyService/Diff in the canonical
// protobuf descriptor and HTTP mapping. Do not edit.


pub const MAX_DIFF_REQUEST_BYTES: usize = {request_limit};
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PolicyDiffServiceClientFailure {{
    InvalidRequest,
    AuthenticationRejected,
    AdministrationUnavailable,
    Transport,
}}
impl std::fmt::Display for PolicyDiffServiceClientFailure {{
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{ formatter.write_str("policy diff service request failed") }}
}}
impl std::error::Error for PolicyDiffServiceClientFailure {{}}
pub struct PolicyDiffServiceClient {{ http: crate::http_client::HttpClient,}}
impl PolicyDiffServiceClient {{
    pub fn new(transport: super::PolicyPreviewTransport) -> Result<Self, PolicyDiffServiceClientFailure> {{
        let http = crate::http_client::HttpClient::new(transport).map_err(|_| PolicyDiffServiceClientFailure::Transport)?;
        Ok(Self {{ http }})
    }}
    pub fn diff(&self, bearer: &str, request: &super::PolicyDiffRequest) -> Result<super::PolicyDiffResponse, PolicyDiffServiceClientFailure> {{
        let body = request.encode()?;
        if body.len() > MAX_DIFF_REQUEST_BYTES {{ return Err(PolicyDiffServiceClientFailure::InvalidRequest); }}
        let (status, bytes) = self.http.post(bearer, {path:?}, body, {response_limit}).map_err(|_| PolicyDiffServiceClientFailure::Transport)?;
        if !(200..300).contains(&status) {{
            let code = serde_json::from_slice::<serde_json::Value>(&bytes).ok().and_then(|value| value.get("code")?.as_str().map(str::to_owned));
            return Err(match (status, code.as_deref()) {{
                (400, Some("invalid_request")) => PolicyDiffServiceClientFailure::InvalidRequest,
                (401, Some("authentication_rejected")) => PolicyDiffServiceClientFailure::AuthenticationRejected,
                (503, Some("administration_unavailable")) => PolicyDiffServiceClientFailure::AdministrationUnavailable,
                _ => PolicyDiffServiceClientFailure::Transport,
            }});
        }}
        super::PolicyDiffResponse::decode(&bytes)
    }}
}}
"#,
        path = path,
        request_limit = request_limit,
        response_limit = response_limit,
    );
    write_generated("policy_diff_service_client.rs", source)
}
