use std::error::Error;

use super::super::validation::ValidatedOperations;
use super::write_generated;

pub(super) fn generate_policy_test_client(
    operations: &ValidatedOperations,
) -> Result<(), Box<dyn Error>> {
    let operation = operations.operation("positron.v1.PolicyService/Test")?;
    let path = operation.path();
    let request_limit = operation.request_limit();
    let response_limit = operation.response_limit();
    let source = format!(
        r#"// Generated by positron-api/build.rs from PolicyService/Test in the canonical
// protobuf descriptor and HTTP mapping. Do not edit.
use std::io::Read;
use std::time::Duration;
pub const MAX_TEST_REQUEST_BYTES: usize = {request_limit};
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PolicyTestServiceClientFailure {{
    InvalidRequest,
    AuthenticationRejected,
    AdministrationUnavailable,
    Transport,
}}
impl std::fmt::Display for PolicyTestServiceClientFailure {{
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{
        formatter.write_str("policy test service request failed")
    }}
}}
impl std::error::Error for PolicyTestServiceClientFailure {{}}

pub struct PolicyTestServiceClient {{
    endpoint: String,
    client: reqwest::blocking::Client,
}}
impl PolicyTestServiceClient {{
    pub fn new(transport: super::PolicyPreviewTransport) -> Result<Self, PolicyTestServiceClientFailure> {{
        let (endpoint, builder) = match transport {{
            super::PolicyPreviewTransport::PlaintextOptOut {{ endpoint }} => (format!("http://{{endpoint}}"), reqwest::blocking::Client::builder()),
            super::PolicyPreviewTransport::Tls {{ endpoint, server_name, trust_file }} => {{
                let identity = server_name.parse::<std::net::IpAddr>();
                if server_name.is_empty() || server_name.len() > 253 || identity.as_ref().is_ok_and(|ip| *ip != endpoint.ip()) {{
                    return Err(PolicyTestServiceClientFailure::Transport);
                }}
                let authority = match identity {{
                    Ok(std::net::IpAddr::V6(_)) => format!("[{{server_name}}]"),
                    _ => server_name.clone(),
                }};
                let trust = crate::api_keys::read_bounded_trust_file(&trust_file).map_err(|_| PolicyTestServiceClientFailure::Transport)?;
                let certificate = reqwest::Certificate::from_pem(&trust).map_err(|_| PolicyTestServiceClientFailure::Transport)?;
                (format!("https://{{authority}}:{{}}", endpoint.port()), reqwest::blocking::Client::builder().add_root_certificate(certificate).resolve(&server_name, endpoint))
            }},
        }};
        Ok(Self {{
            endpoint,
            client: builder.connect_timeout(Duration::from_secs(5)).timeout(Duration::from_secs(5)).no_proxy().build().map_err(|_| PolicyTestServiceClientFailure::Transport)?,
        }})
    }}
    pub fn test(&self, bearer: &str, request: &super::PolicyTestRequest) -> Result<super::PolicyTestResponse, PolicyTestServiceClientFailure> {{
        let body = request.encode()?;
        if body.len() > MAX_TEST_REQUEST_BYTES {{
            return Err(PolicyTestServiceClientFailure::InvalidRequest);
        }}
        let response = self.client.post(format!("{{}}{path}", self.endpoint)).bearer_auth(bearer).header(reqwest::header::CONTENT_TYPE, "application/json").body(body).send().map_err(|_| PolicyTestServiceClientFailure::Transport)?;
        let status = response.status().as_u16();
        let mut bytes = Vec::with_capacity({response_limit});
        response.take(({response_limit} + 1) as u64).read_to_end(&mut bytes).map_err(|_| PolicyTestServiceClientFailure::Transport)?;
        if bytes.len() > {response_limit} {{
            return Err(PolicyTestServiceClientFailure::Transport);
        }}
        if !(200..300).contains(&status) {{
            let code = serde_json::from_slice::<serde_json::Value>(&bytes).ok().and_then(|value| value.get("code")?.as_str().map(str::to_owned));
            return Err(match (status, code.as_deref()) {{
                (400, Some("invalid_request")) => PolicyTestServiceClientFailure::InvalidRequest,
                (401, Some("authentication_rejected")) => PolicyTestServiceClientFailure::AuthenticationRejected,
                (503, Some("administration_unavailable")) => PolicyTestServiceClientFailure::AdministrationUnavailable,
                _ => PolicyTestServiceClientFailure::Transport,
            }});
        }}
        super::PolicyTestResponse::decode(&bytes)
    }}
}}
"#,
        path = path,
        request_limit = request_limit,
        response_limit = response_limit,
    );
    write_generated("policy_test_service_client.rs", source)
}
