use std::error::Error;

use super::super::validation::ValidatedOperations;
use super::write_generated;

pub(super) fn generate_policy_activate_client(
    operations: &ValidatedOperations,
) -> Result<(), Box<dyn Error>> {
    let operation = operations.operation("positron.v1.PolicyService/Activate")?;
    let path = operation.path();
    let request_limit = operation.request_limit();
    let response_limit = operation.response_limit();
    let source = format!(
        r#"// Generated by positron-api/build.rs from PolicyService/Activate in the canonical
// protobuf descriptor and HTTP mapping. Do not edit.
use std::io::Read;
use std::time::Duration;
pub const MAX_ACTIVATE_REQUEST_BYTES: usize = {request_limit};
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum PolicyActivateServiceClientFailure {{
    InvalidRequest,
    AuthenticationRejected,
    StaleGeneration {{ resource_generation: u64, semantic_diff: String }},
    IdempotencyConflict,
    AdministrationUnavailable,
    Transport,
}}
impl std::fmt::Display for PolicyActivateServiceClientFailure {{
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{ formatter.write_str("policy activate service request failed") }}
}}
impl std::error::Error for PolicyActivateServiceClientFailure {{}}
pub struct PolicyActivateServiceClient {{ endpoint: String, client: reqwest::blocking::Client }}
impl PolicyActivateServiceClient {{
    pub fn new(transport: super::PolicyPreviewTransport) -> Result<Self, PolicyActivateServiceClientFailure> {{
        let (endpoint, builder) = match transport {{
            super::PolicyPreviewTransport::PlaintextOptOut {{ endpoint }} => (format!("http://{{endpoint}}"), reqwest::blocking::Client::builder()),
            super::PolicyPreviewTransport::Tls {{ endpoint, server_name, trust_file }} => {{
                let identity = server_name.parse::<std::net::IpAddr>();
                if server_name.is_empty() || server_name.len() > 253 || identity.as_ref().is_ok_and(|ip| *ip != endpoint.ip()) {{ return Err(PolicyActivateServiceClientFailure::Transport); }}
                let authority = match identity {{ Ok(std::net::IpAddr::V6(_)) => format!("[{{server_name}}]"), _ => server_name.clone() }};
                let trust = crate::api_keys::read_bounded_trust_file(&trust_file).map_err(|_| PolicyActivateServiceClientFailure::Transport)?;
                let certificate = reqwest::Certificate::from_pem(&trust).map_err(|_| PolicyActivateServiceClientFailure::Transport)?;
                (format!("https://{{authority}}:{{}}", endpoint.port()), reqwest::blocking::Client::builder().add_root_certificate(certificate).resolve(&server_name, endpoint))
            }},
        }};
        Ok(Self {{ endpoint, client: builder.connect_timeout(Duration::from_secs(5)).timeout(Duration::from_secs(5)).no_proxy().build().map_err(|_| PolicyActivateServiceClientFailure::Transport)? }})
    }}
    pub fn activate(&self, bearer: &str, request: &super::PolicyActivateRequest) -> Result<super::PolicyActivateResponse, PolicyActivateServiceClientFailure> {{
        let body = request.encode()?;
        if body.len() > MAX_ACTIVATE_REQUEST_BYTES {{ return Err(PolicyActivateServiceClientFailure::InvalidRequest); }}
        let response = self.client.post(format!("{{}}{path}", self.endpoint)).bearer_auth(bearer).header(reqwest::header::CONTENT_TYPE, "application/json").body(body).send().map_err(|_| PolicyActivateServiceClientFailure::Transport)?;
        let status = response.status().as_u16();
        let mut bytes = Vec::with_capacity({response_limit});
        response.take(({response_limit} + 1) as u64).read_to_end(&mut bytes).map_err(|_| PolicyActivateServiceClientFailure::Transport)?;
        if bytes.len() > {response_limit} {{ return Err(PolicyActivateServiceClientFailure::Transport); }}
        if !(200..300).contains(&status) {{
            let value = serde_json::from_slice::<serde_json::Value>(&bytes).ok();
            let code = value.as_ref().and_then(|value| value.get("code")?.as_str());
            return Err(match (status, code) {{
                (400, Some("invalid_request")) => PolicyActivateServiceClientFailure::InvalidRequest,
                (401, Some("authentication_rejected")) => PolicyActivateServiceClientFailure::AuthenticationRejected,
                (409, Some("stale_generation")) => {{
                    let generation = value.as_ref().and_then(|value| value.get("resource_generation")?.as_u64());
                    let semantic_diff = value.as_ref().and_then(|value| value.get("semantic_diff")?.as_str()).filter(|value| !value.is_empty() && value.len() <= 1024);
                    match (generation, semantic_diff) {{
                        (Some(resource_generation), Some(semantic_diff)) if resource_generation != 0 => PolicyActivateServiceClientFailure::StaleGeneration {{ resource_generation, semantic_diff: semantic_diff.to_owned() }},
                        _ => PolicyActivateServiceClientFailure::Transport,
                    }}
                }},
                (409, Some("idempotency_conflict")) => PolicyActivateServiceClientFailure::IdempotencyConflict,
                (503, Some("administration_unavailable")) => PolicyActivateServiceClientFailure::AdministrationUnavailable,
                _ => PolicyActivateServiceClientFailure::Transport,
            }});
        }}
        super::PolicyActivateResponse::decode(&bytes)
    }}
}}
"#,
        path = path,
        request_limit = request_limit,
        response_limit = response_limit,
    );
    write_generated("policy_activate_service_client.rs", source)
}
