use std::error::Error;

use super::super::validation::ValidatedOperations;
use super::write_generated;

pub(super) fn generate_policy_preview_client(
    operations: &ValidatedOperations,
) -> Result<(), Box<dyn Error>> {
    let operation = operations.operation("positron.v1.PolicyService/Validate")?;
    let path = operation.path();
    let request_limit = operation.request_limit();
    let response_limit = operation.response_limit();
    let source = format!(
        r#"// Generated by positron-api/build.rs from PolicyService/Validate in the canonical
// protobuf descriptor and HTTP mapping. Do not edit.



pub const MAX_REQUEST_BYTES: usize = {request_limit};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PolicyPreviewServiceClientFailure {{
    InvalidRequest,
    AuthenticationRejected,
    AdministrationUnavailable,
    Transport,
}}
impl std::fmt::Display for PolicyPreviewServiceClientFailure {{
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{
        formatter.write_str("policy preview service request failed")
    }}
}}
impl std::error::Error for PolicyPreviewServiceClientFailure {{}}

pub struct PolicyPreviewServiceClient {{
    http: crate::http_client::HttpClient,
}}
impl PolicyPreviewServiceClient {{
    pub fn new(transport: super::PolicyPreviewTransport) -> Result<Self, PolicyPreviewServiceClientFailure> {{
        let http = crate::http_client::HttpClient::new(transport).map_err(|_| PolicyPreviewServiceClientFailure::Transport)?;
        Ok(Self {{ http }})
    }}
    pub fn validate(&self, bearer: &str, request: &super::PolicyPreviewRequest) -> Result<super::PolicyValidateResponse, PolicyPreviewServiceClientFailure> {{
        let body = request.encode().map_err(|_| PolicyPreviewServiceClientFailure::InvalidRequest)?;
        if body.len() > MAX_REQUEST_BYTES {{ return Err(PolicyPreviewServiceClientFailure::InvalidRequest); }}
        let (status, bytes) = self.http.post(bearer, {path:?}, body, {response_limit}).map_err(|_| PolicyPreviewServiceClientFailure::Transport)?;
        if !(200..300).contains(&status) {{
            let code = serde_json::from_slice::<serde_json::Value>(&bytes).ok().and_then(|value| value.get("code")?.as_str().map(str::to_owned));
            return Err(match (status, code.as_deref()) {{
                (400, Some("invalid_request")) => PolicyPreviewServiceClientFailure::InvalidRequest,
                (401, Some("authentication_rejected")) => PolicyPreviewServiceClientFailure::AuthenticationRejected,
                (503, Some("administration_unavailable")) => PolicyPreviewServiceClientFailure::AdministrationUnavailable,
                _ => PolicyPreviewServiceClientFailure::Transport,
            }});
        }}
        super::PolicyValidateResponse::decode(&bytes).map_err(|_| PolicyPreviewServiceClientFailure::Transport)
    }}
}}
"#,
        path = path,
        request_limit = request_limit,
        response_limit = response_limit,
    );
    write_generated("policy_preview_service_client.rs", source)
}
