use std::error::Error;

use super::super::validation::ValidatedOperations;
use super::write_generated;

pub(super) fn generate_tenant_alias_client(
    operations: &ValidatedOperations,
) -> Result<(), Box<dyn Error>> {
    let operation = operations.operation("positron.v1.TenantAliasService/Bind")?;
    let path = operation.path();
    let request_limit = operation.request_limit();
    let response_limit = operation.response_limit();
    let source = format!(
        r#"// Generated by positron-api/build.rs from TenantAliasService/Bind in the canonical
// protobuf descriptor and HTTP mapping. Do not edit.



#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum TenantAliasServiceClientFailure {{
    InvalidRequest,
    AuthenticationRejected,
    TenantUnavailable,
    StaleGeneration,
    IdempotencyConflict,
    AliasAlreadyBound,
    AliasConflict,
    AdministrationUnavailable,
    Transport,
}}
impl std::fmt::Display for TenantAliasServiceClientFailure {{
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{
        formatter.write_str("tenant alias service request failed")
    }}
}}
impl std::error::Error for TenantAliasServiceClientFailure {{}}

pub struct TenantAliasServiceClient {{ http: crate::http_client::HttpClient,}}
impl TenantAliasServiceClient {{
    pub fn new(transport: super::TenantAliasTransport) -> Result<Self, TenantAliasServiceClientFailure> {{
        let http = crate::http_client::HttpClient::new(transport).map_err(|_| TenantAliasServiceClientFailure::Transport)?;
        Ok(Self {{ http }})
    }}
    pub fn bind(&self, bearer: &str, request: &super::TenantAliasBindRequest) -> Result<super::TenantAliasBindResponse, TenantAliasServiceClientFailure> {{
        let body = request.encode().map_err(|_| TenantAliasServiceClientFailure::InvalidRequest)?;
        if body.len() > {request_limit} {{ return Err(TenantAliasServiceClientFailure::InvalidRequest); }}
        let (status, bytes) = self.http.post(bearer, {path:?}, body, {response_limit}).map_err(|_| TenantAliasServiceClientFailure::Transport)?;
        if !(200..300).contains(&status) {{
            let value = serde_json::from_slice::<serde_json::Value>(&bytes).ok();
            let code = value.as_ref().and_then(|value| value.get("code")?.as_str());
            return Err(match (status, code) {{
                (400, Some("invalid_request")) => TenantAliasServiceClientFailure::InvalidRequest,
                (401, Some("authentication_rejected")) => TenantAliasServiceClientFailure::AuthenticationRejected,
                (404, Some("tenant_unavailable")) => TenantAliasServiceClientFailure::TenantUnavailable,
                (409, Some("stale_generation")) => TenantAliasServiceClientFailure::StaleGeneration,
                (409, Some("idempotency_conflict")) => TenantAliasServiceClientFailure::IdempotencyConflict,
                (409, Some("alias_already_bound")) => TenantAliasServiceClientFailure::AliasAlreadyBound,
                (409, Some("alias_conflict")) => TenantAliasServiceClientFailure::AliasConflict,
                (503, Some("administration_unavailable")) => TenantAliasServiceClientFailure::AdministrationUnavailable,
                _ => TenantAliasServiceClientFailure::Transport,
            }});
        }}
        super::TenantAliasBindResponse::decode(&bytes).map_err(|_| TenantAliasServiceClientFailure::Transport)
    }}
}}
"#,
        path = path,
        request_limit = request_limit,
        response_limit = response_limit,
    );
    write_generated("tenant_alias_service_client.rs", source)
}
