use std::error::Error;

use super::super::validation::ValidatedOperations;
use super::write_generated;

pub(super) fn generate_tenant_service_client(
    operations: &ValidatedOperations,
) -> Result<(), Box<dyn Error>> {
    let create = operations
        .operation("positron.v1.TenantService/Create")?
        .path();
    let inspect = operations
        .operation("positron.v1.TenantService/Inspect")?
        .path();
    let list = operations
        .operation("positron.v1.TenantService/List")?
        .path();
    let update = operations
        .operation("positron.v1.TenantService/UpdateDisplayName")?
        .path();
    let source = format!(
        r#"// Generated by positron-api/build.rs from TenantService in the canonical HTTP mapping. Do not edit.
use std::io::Read; use std::time::Duration;
#[derive(Clone,Copy,Debug,Eq,PartialEq)] pub enum TenantServiceClientFailure {{ InvalidRequest, AuthenticationRejected, TenantUnavailable, StaleGeneration, StaleContinuation, IdempotencyConflict, AdministrationUnavailable, Transport }}
impl std::fmt::Display for TenantServiceClientFailure {{ fn fmt(&self,f:&mut std::fmt::Formatter<'_>)->std::fmt::Result{{f.write_str("tenant service request failed")}} }} impl std::error::Error for TenantServiceClientFailure {{}}
pub struct TenantServiceClient {{ endpoint:String, client:reqwest::blocking::Client }}
impl TenantServiceClient {{ pub fn new(transport:super::TenantServiceTransport)->Result<Self,TenantServiceClientFailure>{{let(endpoint,builder)=match transport{{super::TenantServiceTransport::PlaintextOptOut{{endpoint}}=>(format!("http://{{endpoint}}"),reqwest::blocking::Client::builder()),super::TenantServiceTransport::Tls{{endpoint,server_name,trust_file}}=>{{let ip=server_name.parse::<std::net::IpAddr>();if server_name.is_empty()||server_name.len()>253||ip.as_ref().is_ok_and(|ip|*ip!=endpoint.ip()){{return Err(TenantServiceClientFailure::Transport)}}let trust=crate::api_keys::read_bounded_trust_file(&trust_file).map_err(|_|TenantServiceClientFailure::Transport)?;let certificate=reqwest::Certificate::from_pem(&trust).map_err(|_|TenantServiceClientFailure::Transport)?;let authority=match ip{{Ok(std::net::IpAddr::V6(_))=>format!("[{{server_name}}]"),_=>server_name.clone()}};(format!("https://{{authority}}:{{}}",endpoint.port()),reqwest::blocking::Client::builder().add_root_certificate(certificate).resolve(&server_name,endpoint))}}}};Ok(Self{{endpoint,client:builder.connect_timeout(Duration::from_secs(5)).timeout(Duration::from_secs(5)).no_proxy().build().map_err(|_|TenantServiceClientFailure::Transport)?}})}}
fn send(&self, bearer: &str, path: &str, body: Vec<u8>) -> Result<Vec<u8>, TenantServiceClientFailure> {{
    if body.len() > super::MAX_REQUEST_BYTES {{
        return Err(TenantServiceClientFailure::InvalidRequest);
    }}
    let response = self.client.post(format!("{{}}{{path}}", self.endpoint)).bearer_auth(bearer).header(reqwest::header::CONTENT_TYPE, "application/json").body(body).send().map_err(|_| TenantServiceClientFailure::Transport)?;
    let status = response.status().as_u16();
    let mut bytes = Vec::with_capacity(super::MAX_RESPONSE_BYTES);
    response.take((super::MAX_RESPONSE_BYTES + 1) as u64).read_to_end(&mut bytes).map_err(|_| TenantServiceClientFailure::Transport)?;
    if bytes.len() > super::MAX_RESPONSE_BYTES {{
        return Err(TenantServiceClientFailure::Transport);
    }}
    if !(200..300).contains(&status) {{
        let code = serde_json::from_slice::<serde_json::Value>(&bytes).ok().and_then(|value| value.get("code")?.as_str().map(str::to_owned));
        return Err(match (status, code.as_deref()) {{
            (400, Some("invalid_request")) => TenantServiceClientFailure::InvalidRequest,
            (401, Some("authentication_rejected")) => TenantServiceClientFailure::AuthenticationRejected,
            (404, Some("tenant_unavailable")) => TenantServiceClientFailure::TenantUnavailable,
            (409, Some("stale_display_generation")) => TenantServiceClientFailure::StaleGeneration,
            (409, Some("stale_continuation")) => TenantServiceClientFailure::StaleContinuation,
            (409, Some("idempotency_conflict")) => TenantServiceClientFailure::IdempotencyConflict,
            (503, Some("administration_unavailable")) => TenantServiceClientFailure::AdministrationUnavailable,
            _ => TenantServiceClientFailure::Transport,
        }});
    }}
    Ok(bytes)
}}
pub fn create(&self,b:&str,r:&super::TenantCreateRequest)->Result<super::TenantCreateResponse,TenantServiceClientFailure>{{super::TenantCreateResponse::decode(&self.send(b,{create:?},r.encode().map_err(|_|TenantServiceClientFailure::InvalidRequest)?)?).map_err(|_|TenantServiceClientFailure::Transport)}} pub fn inspect(&self,b:&str,r:&super::TenantInspectRequest)->Result<super::TenantInspectResponse,TenantServiceClientFailure>{{super::TenantInspectResponse::decode(&self.send(b,{inspect:?},r.encode().map_err(|_|TenantServiceClientFailure::InvalidRequest)?)?).map_err(|_|TenantServiceClientFailure::Transport)}} pub fn list(&self,b:&str,r:&super::TenantListRequest)->Result<super::TenantListResponse,TenantServiceClientFailure>{{super::TenantListResponse::decode(&self.send(b,{list:?},r.encode().map_err(|_|TenantServiceClientFailure::InvalidRequest)?)?).map_err(|_|TenantServiceClientFailure::Transport)}} pub fn update_display_name(&self,b:&str,r:&super::TenantDisplayNameUpdateRequest)->Result<super::TenantDisplayNameUpdateResponse,TenantServiceClientFailure>{{super::TenantDisplayNameUpdateResponse::decode(&self.send(b,{update:?},r.encode().map_err(|_|TenantServiceClientFailure::InvalidRequest)?)?).map_err(|_|TenantServiceClientFailure::Transport)}} }}
"#
    );
    write_generated("tenant_service_client.rs", source)
}
