use std::error::Error;

use super::super::validation::ValidatedOperations;
use super::write_generated;

pub(super) fn generate_tenant_lifecycle_client(
    operations: &ValidatedOperations,
) -> Result<(), Box<dyn Error>> {
    let operation = operations.operation("positron.v1.TenantLifecycleService/Transition")?;
    let path = operation.path();
    let request_limit = operation.request_limit();
    let response_limit = operation.response_limit();
    let source = format!(
        r#"// Generated by positron-api/build.rs from TenantLifecycleService/Transition in the canonical protobuf descriptor and HTTP mapping. Do not edit.


pub const MAX_REQUEST_BYTES: usize = {request_limit};
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum TenantLifecycleServiceClientFailure {{ InvalidRequest, AuthenticationRejected, TenantUnavailable, StaleGeneration {{ lifecycle_generation: u64, semantic_diff: String }}, IdempotencyConflict, InvalidTransition, PurgeCompletionUnavailable, AdministrationUnavailable, Transport }}
impl std::fmt::Display for TenantLifecycleServiceClientFailure {{ fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{ f.write_str("tenant lifecycle service request failed") }} }}
impl std::error::Error for TenantLifecycleServiceClientFailure {{}}
pub struct TenantLifecycleServiceClient {{ http: crate::http_client::HttpClient,}}
impl TenantLifecycleServiceClient {{
 pub fn new(transport: super::TenantLifecycleTransport) -> Result<Self, TenantLifecycleServiceClientFailure> {{
        let http = crate::http_client::HttpClient::new(transport).map_err(|_| TenantLifecycleServiceClientFailure::Transport)?;
        Ok(Self {{ http }})
    }}
 pub fn transition(&self,bearer:&str,request:&super::TenantLifecycleTransitionRequest)->Result<super::TenantLifecycleTransitionResponse,TenantLifecycleServiceClientFailure> {{ let body=request.encode().map_err(|_|TenantLifecycleServiceClientFailure::InvalidRequest)?; if body.len()>MAX_REQUEST_BYTES {{ return Err(TenantLifecycleServiceClientFailure::InvalidRequest); }} let (status, bytes) = self.http.post(bearer, {path:?}, body, {response_limit}).map_err(|_| TenantLifecycleServiceClientFailure::Transport)?;
        if !(200..300).contains(&status) {{ let value=serde_json::from_slice::<serde_json::Value>(&bytes).ok(); let code=value.as_ref().and_then(|v|v.get("code")?.as_str()); return Err(match (status,code) {{ (400,Some("invalid_request"))=>TenantLifecycleServiceClientFailure::InvalidRequest,(401,Some("authentication_rejected"))=>TenantLifecycleServiceClientFailure::AuthenticationRejected,(404,Some("tenant_unavailable"))=>TenantLifecycleServiceClientFailure::TenantUnavailable,(409,Some("stale_generation"))=>stale(value.as_ref()),(409,Some("idempotency_conflict"))=>TenantLifecycleServiceClientFailure::IdempotencyConflict,(409,Some("invalid_transition"))=>TenantLifecycleServiceClientFailure::InvalidTransition,(409,Some("purge_completion_unavailable"))=>TenantLifecycleServiceClientFailure::PurgeCompletionUnavailable,(503,Some("administration_unavailable"))=>TenantLifecycleServiceClientFailure::AdministrationUnavailable,_=>TenantLifecycleServiceClientFailure::Transport }}); }} super::TenantLifecycleTransitionResponse::decode(&bytes).map_err(|_|TenantLifecycleServiceClientFailure::Transport) }}
}}
fn stale(value: Option<&serde_json::Value>) -> TenantLifecycleServiceClientFailure {{ let Some(value)=value else {{ return TenantLifecycleServiceClientFailure::Transport; }}; let Some(lifecycle_generation)=value.get("lifecycle_generation").and_then(serde_json::Value::as_u64) else {{ return TenantLifecycleServiceClientFailure::Transport; }}; let Some(semantic_diff)=value.get("semantic_diff").and_then(serde_json::Value::as_str) else {{ return TenantLifecycleServiceClientFailure::Transport; }}; if lifecycle_generation==0 || semantic_diff.is_empty() || semantic_diff.len()>1024 {{ return TenantLifecycleServiceClientFailure::Transport; }} TenantLifecycleServiceClientFailure::StaleGeneration {{ lifecycle_generation,semantic_diff:semantic_diff.to_owned() }} }}
"#,
        path = path,
        request_limit = request_limit,
        response_limit = response_limit
    );
    write_generated("tenant_lifecycle_service_client.rs", source)
}
