use std::error::Error;

use super::super::validation::ValidatedOperations;
use super::write_generated;

pub(super) fn generate_tenant_alias_client(
    operations: &ValidatedOperations,
) -> Result<(), Box<dyn Error>> {
    let operation = operations.operation("positron.v1.TenantAliasService/Bind")?;
    let path = operation.path();
    let request_limit = operation.request_limit();
    let response_limit = operation.response_limit();
    let source = format!(
        r#"// Generated by positron-api/build.rs from TenantAliasService/Bind in the canonical
// protobuf descriptor and HTTP mapping. Do not edit.
use std::io::Read;
use std::time::Duration;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum TenantAliasServiceClientFailure {{
    InvalidRequest,
    AuthenticationRejected,
    TenantUnavailable,
    StaleGeneration,
    IdempotencyConflict,
    AliasAlreadyBound,
    AliasConflict,
    AdministrationUnavailable,
    Transport,
}}
impl std::fmt::Display for TenantAliasServiceClientFailure {{
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{
        formatter.write_str("tenant alias service request failed")
    }}
}}
impl std::error::Error for TenantAliasServiceClientFailure {{}}

pub struct TenantAliasServiceClient {{ endpoint: String, client: reqwest::blocking::Client }}
impl TenantAliasServiceClient {{
    pub fn new(transport: super::TenantAliasTransport) -> Result<Self, TenantAliasServiceClientFailure> {{
        let (endpoint, builder) = match transport {{
            super::TenantAliasTransport::PlaintextOptOut {{ endpoint }} => (format!("http://{{endpoint}}"), reqwest::blocking::Client::builder()),
            super::TenantAliasTransport::Tls {{ endpoint, server_name, trust_file }} => {{
                let identity = server_name.parse::<std::net::IpAddr>();
                if server_name.is_empty() || server_name.len() > 253 || identity.as_ref().is_ok_and(|ip| *ip != endpoint.ip()) {{
                    return Err(TenantAliasServiceClientFailure::Transport);
                }}
                let authority = match identity {{ Ok(std::net::IpAddr::V6(_)) => format!("[{{server_name}}]"), _ => server_name.clone() }};
                let trust = crate::api_keys::read_bounded_trust_file(&trust_file).map_err(|_| TenantAliasServiceClientFailure::Transport)?;
                let certificate = reqwest::Certificate::from_pem(&trust).map_err(|_| TenantAliasServiceClientFailure::Transport)?;
                (format!("https://{{authority}}:{{}}", endpoint.port()), reqwest::blocking::Client::builder().add_root_certificate(certificate).resolve(&server_name, endpoint))
            }},
        }};
        Ok(Self {{ endpoint, client: builder.connect_timeout(Duration::from_secs(5)).timeout(Duration::from_secs(5)).no_proxy().build().map_err(|_| TenantAliasServiceClientFailure::Transport)? }})
    }}
    pub fn bind(&self, bearer: &str, request: &super::TenantAliasBindRequest) -> Result<super::TenantAliasBindResponse, TenantAliasServiceClientFailure> {{
        let body = request.encode().map_err(|_| TenantAliasServiceClientFailure::InvalidRequest)?;
        if body.len() > {request_limit} {{ return Err(TenantAliasServiceClientFailure::InvalidRequest); }}
        let response = self.client.post(format!("{{}}{path}", self.endpoint)).bearer_auth(bearer).header(reqwest::header::CONTENT_TYPE, "application/json").body(body).send().map_err(|_| TenantAliasServiceClientFailure::Transport)?;
        let status = response.status().as_u16();
        let mut bytes = Vec::with_capacity({response_limit});
        response.take(({response_limit} + 1) as u64).read_to_end(&mut bytes).map_err(|_| TenantAliasServiceClientFailure::Transport)?;
        if bytes.len() > {response_limit} {{ return Err(TenantAliasServiceClientFailure::Transport); }}
        else if !(200..300).contains(&status) {{
            let value = serde_json::from_slice::<serde_json::Value>(&bytes).ok();
            let code = value.as_ref().and_then(|value| value.get("code")?.as_str());
            return Err(match (status, code) {{
                (400, Some("invalid_request")) => TenantAliasServiceClientFailure::InvalidRequest,
                (401, Some("authentication_rejected")) => TenantAliasServiceClientFailure::AuthenticationRejected,
                (404, Some("tenant_unavailable")) => TenantAliasServiceClientFailure::TenantUnavailable,
                (409, Some("stale_generation")) => TenantAliasServiceClientFailure::StaleGeneration,
                (409, Some("idempotency_conflict")) => TenantAliasServiceClientFailure::IdempotencyConflict,
                (409, Some("alias_already_bound")) => TenantAliasServiceClientFailure::AliasAlreadyBound,
                (409, Some("alias_conflict")) => TenantAliasServiceClientFailure::AliasConflict,
                (503, Some("administration_unavailable")) => TenantAliasServiceClientFailure::AdministrationUnavailable,
                _ => TenantAliasServiceClientFailure::Transport,
            }});
        }}
        super::TenantAliasBindResponse::decode(&bytes).map_err(|_| TenantAliasServiceClientFailure::Transport)
    }}
}}
"#,
        path = path,
        request_limit = request_limit,
        response_limit = response_limit,
    );
    write_generated("tenant_alias_service_client.rs", source)
}
