use std::error::Error;

use super::super::validation::ValidatedOperations;
use super::write_generated;

pub(super) fn generate_tenant_quota_client(
    operations: &ValidatedOperations,
) -> Result<(), Box<dyn Error>> {
    let operation = operations.operation("positron.v1.TenantQuotaService/Update")?;
    let path = operation.path();
    let request_limit = operation.request_limit();
    let response_limit = operation.response_limit();
    let source = format!(
        r#"// Generated by positron-api/build.rs from TenantQuotaService/Update in the canonical
// protobuf descriptor and HTTP mapping. Do not edit.
use std::io::Read;
use std::time::Duration;

pub const MAX_REQUEST_BYTES: usize = {request_limit};

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum TenantQuotaServiceClientFailure {{
    InvalidRequest,
    AuthenticationRejected,
    StaleGeneration {{ resource_generation: u64, semantic_diff: String }},
    IdempotencyConflict,
    AdministrationUnavailable,
    Transport,
}}
impl std::fmt::Display for TenantQuotaServiceClientFailure {{
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{
        formatter.write_str("tenant quota service request failed")
    }}
}}
impl std::error::Error for TenantQuotaServiceClientFailure {{}}

pub struct TenantQuotaServiceClient {{
    endpoint: String,
    client: reqwest::blocking::Client,
}}
impl TenantQuotaServiceClient {{
    pub fn new(transport: super::TenantQuotaTransport) -> Result<Self, TenantQuotaServiceClientFailure> {{
        let (endpoint, builder) = match transport {{
            super::TenantQuotaTransport::PlaintextOptOut {{ endpoint }} => (format!("http://{{endpoint}}"), reqwest::blocking::Client::builder()),
            super::TenantQuotaTransport::Tls {{ endpoint, server_name, trust_file }} => {{
                let identity = server_name.parse::<std::net::IpAddr>();
                if server_name.is_empty() || server_name.len() > 253 || identity.as_ref().is_ok_and(|ip| *ip != endpoint.ip()) {{
                    return Err(TenantQuotaServiceClientFailure::Transport);
                }}
                let authority = match identity {{ Ok(std::net::IpAddr::V6(_)) => format!("[{{server_name}}]"), _ => server_name.clone() }};
                let trust = crate::api_keys::read_bounded_trust_file(&trust_file).map_err(|_| TenantQuotaServiceClientFailure::Transport)?;
                let certificate = reqwest::Certificate::from_pem(&trust).map_err(|_| TenantQuotaServiceClientFailure::Transport)?;
                (format!("https://{{authority}}:{{}}", endpoint.port()), reqwest::blocking::Client::builder().add_root_certificate(certificate).resolve(&server_name, endpoint))
            }},
        }};
        Ok(Self {{ endpoint, client: builder.connect_timeout(Duration::from_secs(5)).timeout(Duration::from_secs(5)).no_proxy().build().map_err(|_| TenantQuotaServiceClientFailure::Transport)? }})
    }}
    pub fn update(&self, bearer: &str, request: &super::TenantQuotaUpdateRequest) -> Result<super::TenantQuotaUpdateResponse, TenantQuotaServiceClientFailure> {{
        let body = request.encode().map_err(|_| TenantQuotaServiceClientFailure::InvalidRequest)?;
        if body.len() > MAX_REQUEST_BYTES {{ return Err(TenantQuotaServiceClientFailure::Transport); }}
        let response = self.client.post(format!("{{}}{path}", self.endpoint)).bearer_auth(bearer).header(reqwest::header::CONTENT_TYPE, "application/json").body(body).send().map_err(|_| TenantQuotaServiceClientFailure::Transport)?;
        let status = response.status().as_u16();
        let mut bytes = Vec::with_capacity({response_limit});
        response.take(({response_limit} + 1) as u64).read_to_end(&mut bytes).map_err(|_| TenantQuotaServiceClientFailure::Transport)?;
        if bytes.len() > {response_limit} {{ return Err(TenantQuotaServiceClientFailure::Transport); }}
        if !(200..300).contains(&status) {{
            let value = serde_json::from_slice::<serde_json::Value>(&bytes).ok();
            let code = value.as_ref().and_then(|value| value.get("code")?.as_str());
            return Err(match (status, code) {{
                (400, Some("invalid_request")) => TenantQuotaServiceClientFailure::InvalidRequest,
                (401, Some("authentication_rejected")) => TenantQuotaServiceClientFailure::AuthenticationRejected,
                (409, Some("stale_generation")) => stale_generation(value.as_ref()),
                (409, Some("idempotency_conflict")) => TenantQuotaServiceClientFailure::IdempotencyConflict,
                (503, Some("administration_unavailable")) => TenantQuotaServiceClientFailure::AdministrationUnavailable,
                _ => TenantQuotaServiceClientFailure::Transport,
            }});
        }}
        serde_json::from_slice(&bytes).map_err(|_| TenantQuotaServiceClientFailure::Transport)
    }}
}}
fn stale_generation(value: Option<&serde_json::Value>) -> TenantQuotaServiceClientFailure {{
    let Some(value) = value else {{ return TenantQuotaServiceClientFailure::Transport; }};
    let Some(resource_generation) = value.get("resource_generation").and_then(serde_json::Value::as_u64) else {{ return TenantQuotaServiceClientFailure::Transport; }};
    let Some(semantic_diff) = value.get("semantic_diff").and_then(serde_json::Value::as_str) else {{ return TenantQuotaServiceClientFailure::Transport; }};
    if resource_generation == 0 || semantic_diff.is_empty() || semantic_diff.len() > 1024 {{ return TenantQuotaServiceClientFailure::Transport; }}
    TenantQuotaServiceClientFailure::StaleGeneration {{ resource_generation, semantic_diff: semantic_diff.to_owned() }}
}}
"#,
        path = path,
        request_limit = request_limit,
        response_limit = response_limit,
    );
    write_generated("tenant_quota_service_client.rs", source)
}
