use std::error::Error;

use super::super::validation::ValidatedOperations;
use super::write_generated;

pub(super) fn generate_tenant_retention_client(
    operations: &ValidatedOperations,
) -> Result<(), Box<dyn Error>> {
    let preview = operations.operation("positron.v1.TenantRetentionService/Preview")?;
    let preview_path = preview.path();
    let preview_request_limit = preview.request_limit();
    let preview_response_limit = preview.response_limit();
    let update = operations.operation("positron.v1.TenantRetentionService/Update")?;
    let update_path = update.path();
    let update_request_limit = update.request_limit();
    let update_response_limit = update.response_limit();
    let source = format!(
        r#"// Generated by positron-api/build.rs from TenantRetentionService in the canonical protobuf descriptor and HTTP mapping. Do not edit.
use std::io::Read;
use std::time::Duration;
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum TenantRetentionServiceClientFailure {{ InvalidRequest, AuthenticationRejected, TenantUnavailable, InvalidConfirmation, StaleContinuation, StaleGeneration {{ retention_generation: u64, semantic_diff: String }}, IdempotencyConflict, AdministrationUnavailable, Transport }}
impl std::fmt::Display for TenantRetentionServiceClientFailure {{ fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{ formatter.write_str("tenant retention service request failed") }} }}
impl std::error::Error for TenantRetentionServiceClientFailure {{}}
pub struct TenantRetentionServiceClient {{ endpoint: String, client: reqwest::blocking::Client }}
impl TenantRetentionServiceClient {{
 pub fn new(transport: super::TenantRetentionTransport) -> Result<Self, TenantRetentionServiceClientFailure> {{ let (endpoint,builder)=match transport {{ super::TenantRetentionTransport::PlaintextOptOut {{ endpoint }} => (format!("http://{{endpoint}}"), reqwest::blocking::Client::builder()), super::TenantRetentionTransport::Tls {{ endpoint, server_name, trust_file }} => {{ let identity=server_name.parse::<std::net::IpAddr>(); if server_name.is_empty() || server_name.len()>253 || identity.as_ref().is_ok_and(|ip|*ip!=endpoint.ip()) {{ return Err(TenantRetentionServiceClientFailure::Transport); }} let authority=match identity {{ Ok(std::net::IpAddr::V6(_))=>format!("[{{server_name}}]"), _=>server_name.clone() }}; let trust=crate::api_keys::read_bounded_trust_file(&trust_file).map_err(|_|TenantRetentionServiceClientFailure::Transport)?; let certificate=reqwest::Certificate::from_pem(&trust).map_err(|_|TenantRetentionServiceClientFailure::Transport)?; (format!("https://{{authority}}:{{}}",endpoint.port()),reqwest::blocking::Client::builder().add_root_certificate(certificate).resolve(&server_name,endpoint)) }} }}; Ok(Self {{ endpoint, client:builder.connect_timeout(Duration::from_secs(5)).timeout(Duration::from_secs(5)).no_proxy().build().map_err(|_|TenantRetentionServiceClientFailure::Transport)? }}) }}
 pub fn preview(&self,bearer:&str,request:&super::TenantRetentionPreviewRequest)->Result<super::TenantRetentionPreviewResponse,TenantRetentionServiceClientFailure>{{let bytes=self.send(bearer,{preview_path:?},request.encode().map_err(|_|TenantRetentionServiceClientFailure::InvalidRequest)?,{preview_request_limit},{preview_response_limit})?;super::TenantRetentionPreviewResponse::decode(&bytes).map_err(|_|TenantRetentionServiceClientFailure::Transport)}}
 pub fn update(&self,bearer:&str,request:&super::TenantRetentionUpdateRequest)->Result<super::TenantRetentionUpdateResponse,TenantRetentionServiceClientFailure>{{let bytes=self.send(bearer,{update_path:?},request.encode().map_err(|_|TenantRetentionServiceClientFailure::InvalidRequest)?,{update_request_limit},{update_response_limit})?;super::TenantRetentionUpdateResponse::decode(&bytes).map_err(|_|TenantRetentionServiceClientFailure::Transport)}}
 fn send(&self,bearer:&str,path:&str,body:Vec<u8>,request_limit:usize,response_limit:usize)->Result<Vec<u8>,TenantRetentionServiceClientFailure>{{if body.len()>request_limit{{Err(TenantRetentionServiceClientFailure::InvalidRequest)}}else{{let response=self.client.post(format!("{{}}{{path}}",self.endpoint)).bearer_auth(bearer).header(reqwest::header::CONTENT_TYPE,"application/json").body(body).send().map_err(|_|TenantRetentionServiceClientFailure::Transport)?;let status=response.status().as_u16();let mut bytes=Vec::with_capacity(response_limit);response.take((response_limit+1)as u64).read_to_end(&mut bytes).map_err(|_|TenantRetentionServiceClientFailure::Transport)?;if bytes.len()>response_limit{{Err(TenantRetentionServiceClientFailure::Transport)}}else if!(200..300).contains(&status){{let value=serde_json::from_slice::<serde_json::Value>(&bytes).ok();let code=value.as_ref().and_then(|value|value.get("code")?.as_str());Err(match(status,code){{(400,Some("invalid_request"))=>TenantRetentionServiceClientFailure::InvalidRequest,(401,Some("authentication_rejected"))=>TenantRetentionServiceClientFailure::AuthenticationRejected,(404,Some("tenant_unavailable"))=>TenantRetentionServiceClientFailure::TenantUnavailable,(409,Some("invalid_confirmation"))=>TenantRetentionServiceClientFailure::InvalidConfirmation,(409,Some("stale_continuation"))=>TenantRetentionServiceClientFailure::StaleContinuation,(409,Some("stale_generation"))=>stale(value.as_ref()),(409,Some("idempotency_conflict"))=>TenantRetentionServiceClientFailure::IdempotencyConflict,(503,Some("administration_unavailable"))=>TenantRetentionServiceClientFailure::AdministrationUnavailable,_=>TenantRetentionServiceClientFailure::Transport}})}}else{{Ok(bytes)}}}}}}
}}
fn stale(value:Option<&serde_json::Value>)->TenantRetentionServiceClientFailure{{let Some(value)=value else{{return TenantRetentionServiceClientFailure::Transport}};let Some(retention_generation)=value.get("retention_generation").and_then(serde_json::Value::as_u64)else{{return TenantRetentionServiceClientFailure::Transport}};let Some(semantic_diff)=value.get("semantic_diff").and_then(serde_json::Value::as_str)else{{return TenantRetentionServiceClientFailure::Transport}};if retention_generation==0||semantic_diff.is_empty()||semantic_diff.len()>1024{{return TenantRetentionServiceClientFailure::Transport}}TenantRetentionServiceClientFailure::StaleGeneration{{retention_generation,semantic_diff:semantic_diff.to_owned()}}}}
"#,
        preview_path = preview_path,
        preview_request_limit = preview_request_limit,
        preview_response_limit = preview_response_limit,
        update_path = update_path,
        update_request_limit = update_request_limit,
        update_response_limit = update_response_limit
    );
    write_generated("tenant_retention_service_client.rs", source)
}
